// <auto-generated />
namespace BakeryCafe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class dateProd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dateProd));
        
        string IMigrationMetadata.Id
        {
            get { return "202302250837164_dateProd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
